### ISSUE TITLE
Fix docs reference to include_repos

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/bugwarrior#244]
It is inconsistent.  @jrabbit reported that he used `github.include_repos = ....` and it didn't work.  Removing the `github.` prefix seemed to fix it, but I don't think that's what the docs say.

**Comment by irl** [comment]
This is wrong, maybe fixed by something since the bug was reported. I'm using ``github.include_repos`` (as in the docs) and it works.

http://bugwarrior.readthedocs.io/en/latest/services/github.html#include-and-exclude-certain-repositories

Not using the ``github.`` will prompt a message saying to use the ``github.`` IIRC.

**Comment by ralphbean** [comment]
Thanks @irl.  :)
