### ISSUE TITLE
add_tags don't support template filters right

### ISSUE THREAD

**Issue by vitaminless** [ralphbean/bugwarrior#271]
I cannot use a template like this: 

``` python
{{ project | replace(" ", "_") }}
```

This will give an error and no task will be created for the provider.

I guess the reason is that the add_tags string will be split before the template engine renders it, so tried to fix it ... 

I came up with this, at least it works for me:
[bugwarrior.service.**init**.patch.txt](https://github.com/ralphbean/bugwarrior/files/79971/bugwarrior.service.__init__.patch.txt)

**Comment by gdetrez** [comment]
Hi @vitaminless.  Cool that you fixed the issue.

As far as I can see, the file you attached is not a patch but the entire file `bugwarrior/services/__init__.py`, is that correct? That might make it a bit more difficult to apply your changes.

If possible, the easiest thing to do would be that you create a pull request here on github.
Or use `git format-patch` to create an actual patch so that we can more easily apply the changes to the latest code.
Thanks!

**Comment by vitaminless** [comment]
Hey @gdetrez,

I have looked into the current code and just cannot see the if this is still a problem.
I have tried to install a current version with pip, but I struggle with lots of error messages... I use another solution for this since a while.

You can either close the bug or I will investigate further if you want to and try to create a pull request.

**Comment by gdetrez** [comment]
I don't completely understand the original issue. If you can provide steps to reproduce it (with expected/actual result) I can take a look myself.

Alternatively, if you want you can post the errors you get when pip-installing bugwarrior here and we'll try to see if we can fix that.
