### ISSUE TITLE
Inconsistent behavior of `filter_{merge,pull}_requests`

### ISSUE THREAD

**Issue by gdetrez** [ralphbean/bugwarrior#315]
The option `filter_merge_requests` or `filter_pull_requests` is documented in gitlab, github and bitbucket like this

> Although you can filter issues using Common Service Configuration Options, pull requests are not 
> filtered by default. You can filter pull requests by adding the following configuration option:
> 
> {service}.filter_pull_requests = True

Which I understand as
- filter_pull_requests = True :arrow_right: prune pull requests according to the assignee (like issues)
- filter_pull_requests = False :arrow_right: import all pull requests

This correspond to the behavior implemented in the github service.

But in both bitbucket and gitlab the implementation seems to do this instead:
- filter_pull_requests = True :arrow_right: don't import pull requests
- filter_pull_requests = False :arrow_right: import pull requests, pruned according to assignee

That's a tad confusing :confused:

**Comment by gdetrez** [comment]
@gfrivolt in #278 interpreted the documentation in the bitbucket/gitlab way so the text should probably be reworded to avoid possible confusion.

@ralphbean what was your original intent for the option?

**Comment by mathstuf** [comment]
Hrm, looks like I'm the one to blame here :/ . Currently, the `bitbucket` and `gitlab` implementations call it `filter_merge_requests` (since they call it that on those services). Anyways, I think that they could probably be renamed to `include_merge_requests` since it looks like that's what they actually do. A deprecation warning could then be used to nudge people to migrate to the new setting.

**Comment by ryneeverett** [comment]
Now that #642 is merged perhaps they should be renamed `exclude_pull_requests` for consistency.
