### ISSUE TITLE
Support for Debian BTS

### ISSUE THREAD

**Issue by irl** [ralphbean/bugwarrior#327]
The Debian bug tracker (https://www.debian.org/Bugs/) is the primary place where Debian bugs are tracked.

There is a SOAP interface "documented" at:

https://wiki.debian.org/DebbugsSoapInterface

I am planning to package this software in Debian (Debian bug is https://bugs.debian.org/810629) and it would be awesome to also use this for Debian bugs.

**Comment by ralphbean** [comment]
Awesome @irl!

Maybe you could send a note out to a debian list and see if you can solicit a Python developer to build a backend for BTS?  Our general rule here is that we won't write a backend for a service unless we use it personally (it's otherwise hard to be sure that it really works).  However, we gladly accept new maintainers for new backends.. we just need to find someone invested to do the upfront work.  It could be you?  :)

**Comment by irl** [comment]
This seems like a good general rule. I'll keep an eye out for anyone that might be interested to write this, and I'll send a message out once the package is accepted in Debian.

If time allows in the future, it may be me that writes this.

**Comment by irl** [comment]
There is a Python library available for accessing the Debian BTS. (:

https://github.com/venthur/python-debianbts/blob/master/src/debianbts.py

This is quickly creeping into my list of things that if I do sooner will make things easier later.
