### ISSUE TITLE
Cut a new bugwarrior release (2.0.0)

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/bugwarrior#339]
I think we're about due.

**Comment by ralphbean** [comment]
Any objections?  Should we wait for any pending fixes first?

**Comment by irl** [comment]
I'll be ready to upload a package to Debian as soon as the release is cut.

**Comment by ryneeverett** [comment]
@irl What about #330?

@ralphbean Given that we don't do point releases, cutting a release right after a bunch of changes and before the development branch has been tested out by multiple developers doesn't make much sense to me. Seems pretty likely that we've introduced some silly regressions. My thinking is that if you don't do point releases, all releases should be stable. Therefore it makes sense to cut a release when the development branch has been quiet for a while. I don't really care though, because I always use a development version. Your call.

**Comment by irl** [comment]
#330 is a problem. I can produce simple man pages though, as these are not complex commands. The bug is resolved in Debian by having a man page, not by having complete documentation in the man page. The man pages just need to describe basically what the command does and where to find the full docs (which are installed in HTML format by the Debian package also).

**Comment by irl** [comment]
Ok, wait a minute. I broke a thing in the Trac tests (test is broken, not the code).

**Comment by ryneeverett** [comment]
Also, any idea what broke Travis?

**Comment by irl** [comment]
Seems to be some sort of missing dependency.

**Comment by ralphbean** [comment]
> Therefore it makes sense to cut a release when the development branch has been quiet for a while.

I'm fine with waiting a week.

> #330 is a problem. I can produce simple man pages though, as these are not complex commands.

I'd rather not add a man page to this repo if we can (I like [help2man](https://www.gnu.org/software/help2man/) for things like this).  But if that doesn't work for some reason, of course we could accept a manpage here.

**Comment by irl** [comment]
help2man is fine. (:

**Comment by ralphbean** [comment]
>> Therefore it makes sense to cut a release when the development branch has been quiet for a while.
> I'm fine with waiting a week.

Checking in.  Any concerns with cutting a release sometime this week?

**Comment by ryneeverett** [comment]
I think it would be good to confirm if #350 was an issue in 1.4.0. If it is a regression caused by #331 I'd hope to fix it before release.

**Comment by ryneeverett** [comment]
Sounds like #350 is not a regression so I'd say go for it.

**Comment by ryneeverett** [comment]
@ralphbean Per @gdetrez's suggestion, if you cut a release in the near future I'd recommend checking out 1aa682865a4e3aa540e047959138d1fb8896c8fb (the last commit before python3 compatibility) since there are likely still some python2 regressions we haven't yet discovered and we certainly haven't fixed all the python3 bugs yet.

**Comment by irl** [comment]
@ralphbean If we're going to release with Python 3 support, I'd be changing the Debian package to Python 3 and there may be enough changes here that maybe we call it 2.0.0? Not sure about the roadmap, just a suggestion.

**Comment by ralphbean** [comment]
2.0.0 sounds like the right target at this point.  Let's keep it in develop for a little bit longer since we just mixed things up with Python3.  :)

**Comment by irl** [comment]
@ralphbean Just checking in on the progress, and a reminder that Debian will be coming up to a freeze and if 2.0.0 is to make it into Debian stretch, it needs to be soon.

**Comment by ralphbean** [comment]
Hey team, any feedback on the python3 stability?  Are we looking safe for a 2.0.0 release?

**Comment by ryneeverett** [comment]
I doubt very many people have tested out python3 yet. However, I'm not sure that's a problem as long as python2 is stable (which I believe it is). I'd recommend packagers to continue to use python2, but the reality is most people are going to pip install with whatever their distro ships by default -- the best we can do for them is give them the best version of bugwarrior we have, which I believe is in `develop` now.

**Comment by ryneeverett** [comment]
Also, it would be nice if #395 made it in before release.

**Comment by xeor** [comment]
ETA? :) Looking forward to the py3 support! For what I can see, the issues discussed above are more or less solved, except the man pages being a little unstructured.

https://github.com/ralphbean/bugwarrior/network - `develop` is leading the race... Will pip installing that give me what will become 2 soon?

**Comment by ryneeverett** [comment]
@xeor Yes, `develop` has all the latest changes that will go into 2.0. In my opinion py3 support likely still has a number of bugs and it would be great if you could test it out and report (in separate issues). Otherwise you'll see the same bugs in the release.

**Comment by ralphbean** [comment]
OK, I ended up cutting 1.5.1, available here:  https://pypi.python.org/pypi/bugwarrior/1.5.1
