### ISSUE TITLE
More extensive documentation for bugwarrior-vault usage required

### ISSUE THREAD

**Issue by Tzrlk** [ralphbean/bugwarrior#526]
After getting `bugwarrior-vault` working after a lot of fiddling, the following points should be covered in the documentation.
* The `-i` or `--interactive` option must be used for each invocation of `bugwarrior-pull` for `@oracle:ask_pass`. If using `@oracle:use_keychain`, this only needs to be done once.
* To use the keychain at all, the python package `bugwarrior[keychain]` needs to be installed, and packages for `python-devel`, `dbus-devel`, and `dbus-glib-devel` need to be installed prior to that so it can compile.

**Comment by renestalder** [comment]
Another note, which I had to check out the code to actually understand how to use it:

For bugwarrior-vault set to work, the bugwarriorrc has to have an @oracle:use_keyring in any configuration. One can basically not set credentials first and then apply it in the configuration. You have to set up the configuration and then go into the vault to set the credentials.

**Comment by ryneeverett** [comment]
The original points seem to have been mostly addressed and I'm addressing @renestalder's in #899.

- --interactive=True is the default. Maybe that wasn't the case when this issue was created? It seems kind of obvious that disabling this would prevent a password prompt.
- It is now documented that bugwarrior[keychain] is required. In the installation docs we link to the upstream keyring package which says to install dbus-python as a prerequisite.
