### ISSUE TITLE
ERROR:bugwarrior.db:Multiple matches

### ISSUE THREAD

**Issue by Mte90** [ralphbean/bugwarrior#601]
I updated to 1.6.0 and I am getting this error.
As I can see there are #447 and #220 that are similar to my problem.
In my case:
```
ERROR:bugwarrior.db:Multiple matches: Issue 582: Modal for keyboard shortcuts - https://github.com/GlotPress/GlotPress-WP/issues/582 matched multiple IDs: {UUID('2729bd0e-bc48-4268-bce0-a8c2ce4ee874'), UUID('580942cf-c0f0-46fa-b80d-215523802102')}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/db.py", line 342, in synchronize
    tw, key_list, issue, legacy_matching=legacy_matching
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/db.py", line 206, in find_local_uuid
    possibilities
```
Seems that generate an error but there is no management on fix them, maybe ignore it because they already exist?

**Comment by pawamoy** [comment]
I have the same issue.

It comes from the fact that I pull issues for 2 or more different namespaces, with an additional `involves:org/user` query.  It means the same issue appear once for namespace1, and a second time for namespace2, because namespace1 opened it on a namespace2 project (namespace1 is my main account, namespace2 is an organization).

What I would like to be able to do is tell bugwarrior **not to consider namespace for unicity**. In other words, if an issue is pulled and matches an existing one **but with a different namespace**, it should not be added a second time.

Actually I would like to discard completely the namespace UDA as I have no use for it and it changes depending on the request, and it causes a "multiple possibilities" error when pulling a second time.

I think I'll try to do that with a taswarrior hook and report back.

**Comment by pawamoy** [comment]
Nope, does not work with hooks, as they operate *after* bugwarrior tries to identify unique tasks. I opened #623 to be able to fix that.

**Comment by ralphbean** [comment]
Ah, I think this may not be a `self.username` assumption.  The `url` for the issue is used as the unique key and having multiple targets enabled that can pull the same issue will have duplicate urls.

I thought for a bit if we could start using the `target` name as a mandatory UDA to distinguish between these.  That would allow bugwarrior to treat them as different.  Each would get the same annotation updates in the future (and any other modifications like summary changes).  But, this isn't what you want in your task list -- two duplicates of the same upstream thing which appear only because you're trying to combine two different methods of filtering in two different target definitions.

----

Once we get duplicates in the task database, recovering from that situation is really tricky.

I'm going to try and focus on de-duplicating tasks *before* they get their uuids assigned, early on in the processing in `db.py`.
