### ISSUE TITLE
Clarify behavior of gitlab.include_todos in light of new membership filter

### ISSUE THREAD

**Issue by ralphbean** [ralphbean/bugwarrior#661]
See discussion in #612.

**Comment by doronbehar** [comment]
Could you elaborate please? I won't mind submitting a patch to the documentation or any other parts if needed. Just to note, I've tried setting `gitlab.include_all_todos` instead of `gitlab.include_todos` and I got the same behaviour as before.. This means it's not only an issue with the documentation..

**Comment by ralphbean** [comment]
Yeah, I think the change to add `gitlab.membership` *broke* the expected behavior of `gitlab.include_todos`.  We should verify this, and either fix it or update the documentation.  (I bet it is a code change to get `include_todos` working again as you expect).
