### ISSUE TITLE
how to use a diff project xxx.yyy than using the gitlab project

### ISSUE THREAD

**Issue by thevikas** [ralphbean/bugwarrior#968]
My setup has different project codes. How to use that diff project name xxx.yyy? the pull is moving those projects back to orig gitlab project name.

**Comment by ryneeverett** [comment]
There are two different ways you could handle this, both documented on the [Common Configuration page](https://bugwarrior-docs.readthedocs.io/en/latest/common_configuration.html):

1. Field Templates: If you can use templating (`gitlab.project_template = {{xxx}}.{{yyy}}`) or a static name for each service section (`gitlab.project_template = xxx.yyy`), this would work.
2. Static Field: If there's no way to do this automatically you can prevent bugwarrior from updating specified fields (`static_fields = project`). Note that this will prevent the project field from being updated (after the initial pull) for all services and I don't believe there's a way to do it on a per-service basis at the moment. However, this is unlikely to be a problem because project fields specifically tend not to change.

**Comment by thevikas** [comment]
I'm using project trees in my tasks. So I could use `gitlab.project_template = genealogy.backend`?
I cannot use the project name from git pull cause its just "backend"
Have already tried `gitlab.project_name` but did not work.

**Comment by ryneeverett** [comment]
It sounds like `gitlab.project_template = genealogy.{{project}}` is what you're after.
